spring:
  main:
    banner-mode: off
  application:
    name: cv
  datasource:
    url:
    username:
    password:
logging:
  level:
    ROOT: ERROR
    be: INFO
#  file:
#    path: /var/log/${spring.application.name}