spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: clientId
            client-secret: clientSecret
  main:
    banner-mode: off
  application:
    name: cv
  datasource:
    url:
    username:
    password:
logging:
  level:
    ROOT: ERROR
    be: INFO
#  file:
server:
  port: 8081
#    path: /var/log/${spring.application.name}