spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${OAUTH2_GITHUB_CLIENT_ID}
            client-secret: ${OAUTH2_GITHUB_CLIENT_SECRET}
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
  main:
    banner-mode: off
  application:
    name: cv
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
logging:
  level:
    ROOT: ERROR
    be: INFO
#  file:
server:
  port: ${PORT:8081}
oauth2:
  provider-attributes:
    google:
      uid: "email"
      name: "name"
      email: "email"
      username: "email"
      picture: "picture"
    github:
      uid: "id"
      name: "name"
      email: "email"
      username: "login"
      picture: "avatar_url"
#    path: /var/log/${spring.application.name}