env: standard
runtime: nodejs14
instance_class: F1

handlers:
  - url: /static/(.*)
    static_files: build/static/\1
    upload: build/static/(.*)
  - url: /assets/(.*)
    static_files: build/assets/\1
    upload: build/assets/(.*)
  - url: /(.*\.(webp|manifest|png|svg|ico|txt|xml))$
    static_files: build/\1
    upload: build/.*\.(webp|manifest|png|svg|ico|txt|xml)$
  - url: /
    static_files: build/index.html
    upload: build/index.html
  - url: /.*
    static_files: build/index.html
    upload: build/index.html