oauth2:
  provider-attributes:
    google:
      uid: "email"
      name: "name"
      email: "email"
      username: "email"
      picture: "picture"
    github:
      uid: "id"
      name: "name"
      email: "email"
      username: "login"
      picture: "avatar_url"