spring:
  cloud:
    gcp:
      sql:
        database-name: ${sm://sql-database-name}
        instance-connection-name: ${sm://sql-instance-connection-name}
  datasource:
    username: ${sm://sql-username}
    password: ${sm://sql-password}
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${sm://oauth2-github-client-id}
            secret-id: ${sm://oauth2-github-secret-id}
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"