runtime: java11
instance_class: F2
inbound_services:
  - warmup
env_variables:
  SPRING_PROFILES_ACTIVE: gcp
  JAVA_USER_OPTS: -XX:TieredStopAtLevel=1 -noverify
automatic_scaling:
  min_instances: 1
  max_instances: 3