version: "3"
services:
  blog-test-db:
    image: postgres:11-alpine
    ports:
      - 7532:5432
    environment:
      - POSTGRES_DB=blog_db_ut
      - POSTGRES_USER=blog
      - POSTGRES_PASSWORD=admin_ut