name: Publish Website
on: push
jobs:
  FTP-Deploy-Action:
    name: Deploy host
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout repo
        with:
          fetch-depth: 2
      - name: Setup Node.js 12
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: Build project
        run: |
          npm install
          npm run build
      - name: Upload to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}