name: Publish Website
on: push
jobs:
  Publish:
    name: Build & Upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout repo
        with:
          fetch-depth: 2
      - name: Generate sitemap
        uses: cicirello/generate-sitemap@v1.6.1
        with:
          base-url-path: https://www.mathiasbosman.be
      - name: Create google verification
        env:
          GOOGLE_CODE: ${{ secrets.GOOGLE_VERIFICATION_CODE }}
        run: |
          echo "google-site-verification: $GOOGLE_CODE.html" > "$GOOGLE_CODE".html
      - name: Setup Node.js 12
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: Build project
        run: |
          npm install
          npm run build
          npm run clean
          npm install --production
      - name: Upload to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ${{ secrets.FTP_PROTOCOL }}
          server-dir: ${{ secrets.FTP_SERVER_DIR }}
          exclude: .git
            - **/*.{git,scss,gitignore,md,npmrc}
            - **/*.package.json
            - **/*.package-lock.json