name: Publish Website
on:
  release:
    types: [published]
jobs:
  Publish:
    name: Build & Upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout repo
        with:
          fetch-depth: 2
      - name: Generate sitemap
        uses: cicirello/generate-sitemap@v1.6.1
        with:
          path-to-root: cv-app/src/main/frontend/public
          base-url-path: https://www.mathiasbosman.be
      - name: Create Google verification
        env:
          GOOGLE_CODE: ${{ secrets.GOOGLE_VERIFICATION_CODE }}
        run: |
          echo "./cv-app/src/main/frontend/public/google-site-verification: $GOOGLE_CODE.html" > "$GOOGLE_CODE".html
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Use gcloud CLI
        run: gcloud info
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -B package --file pom.xml

#TODO deploy