name: GCP Deploy
on:
  release:
    types: [ published ]
jobs:
  Deploy:
    name: Deployment to GCP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Update version
        if: ${{ github.event.release.tag_name }}
        env:
          NEW_VERSION: ${{ github.event.release.tag_name }}
        run: mvn versions:set -DnewVersion=$NEW_VERSION

      - name: Deploy with Maven
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -DskipTests -B clean package appengine:deploy