name: Test timestamp
on: push
jobs:
  Deploy:
    name: Deployment to GCP
    runs-on: ubuntu-latest
    steps:
      - name: Update sitemap
        # echo $(date +'%Y-%m-%d')T00:00:00+00:00
        run: echo $(date +'%Y-%m-%d')T00:00:00+00:00